local_backend: true

backend:
  name: git-gateway
  repo: Lukman10a/markazulbayaan
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
# publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "/public/_posts/"
    create: true
    format: "frontmatter"
    title: "{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
        }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
