local_backend: true

backend:
  name: git-gateway
  repo: Lukman10a/markazulbayaan
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
# publish_mode: editorial_workflow

# slug:
#   encoding: "ascii"
#   clean_accents: true
#   sanitize_replacement: "_"

collections:
  - name: "blog"
    label: "Blog"
    folder: "/public/_posts/"
    create: true
    format: "frontmatter"
    title: "{{title}}"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
        }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Featured Post",
          name: "featured",
          widget: "boolean",
          default: false,
          required: false,
          hint: "Mark this post as featured to display it on the homepage",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # New Featured Collection
  - name: "featured"
    label: "Featured Posts"
    folder: "/public/_featured/"
    create: true
    format: "frontmatter"
    title: "Featured {{title}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "featured",
        }
      - {
          label: "Title",
          name: "title",
          widget: "relation",
          collection: "blog", # Link to the blog collection
          search_fields: ["title"],
          value_field: "{{title}}",
          display_fields: ["title"],
        }
      - {
          label: "Post to Feature",
          name: "post",
          widget: "relation",
          collection: "blog", # Link to the blog collection
          search_fields: ["title"],
          value_field: "{{slug}}", # Store the slug of the blog post
          display_fields: ["title"],
        }
